export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const TOGGLE_PHOTO_CONTAINER = "TOGGLE_PHOTO_CONTAINER";
export const SET_SELECTED_PHOTOS = "SET_SELECTED_PHOTOS";
export const UPLOAD_NEW_PHOTO = "UPLOAD_NEW_PHOTO";

export const CREATE_LOGIN_USER = "CREATE_LOGIN_USER";
export const SET_CREATING_USER = "SET_CREATING_USER";
