export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const TOGGLE_PHOTO_CONTAINER = "TOGGLE_PHOTO_CONTAINER";
export const SET_SELECTED_PHOTOS = "SET_SELECTED_PHOTOS";
export const UPLOAD_NEW_PHOTO = "UPLOAD_NEW_PHOTO";
export const SET_NEW_USER_PHOTOS = "SET_NEW_USER_PHOTOS";

export const CREATE_LOGIN_USER = "CREATE_LOGIN_USER";
export const SET_CREATING_USER = "SET_CREATING_USER";
export const SET_SHOW_USER_FORM = "SET_SHOW_USER_FORM";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_IMAGES_UPLOADING = "SET_IMAGES_UPLOADING";
